# Complete Numpy Tutorial by Manthan Panchal

##### Numpy is a python library used to work specifically in arrays 

##### It has functions for Linear domain, Fourrier Domain,  and Matrices 

##### we can have 1D arrays 2D arrays 3D arrays 4d arrays etc

In [2]:
import numpy as np

##### The basics

In [20]:
A = np.array([1,2,3], dtype = 'int16')
A

array([1, 2, 3], dtype=int16)

In [5]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
#GET DTYPE
A.dtype, B.dtype

(dtype('int16'), dtype('int32'))

In [19]:
#GET DIM
B.ndim

2

In [24]:
#GET SIZE
C.nbytes

36

In [10]:
#GET SHAPE
C.shape

(3, 3)

##### Sclicing

In [14]:
C[2,1]

8

In [15]:
C[:,1]

array([2, 5, 8])

In [18]:
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### Acessing / changing specific elements,  rows and columns

In [12]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [13]:
#getting specific element 
#syntax object[row, column, stepsize]
a[2, 2]

13

In [14]:
a[1, 4]

10

In [15]:
#getting specific column 
a[:, 2]

array([ 3,  8, 13])

In [16]:
a[:, 4]

array([ 5, 10, 15])

In [18]:
#getting specific row
a[0,:]

array([1, 2, 3, 4, 5])

In [20]:
a[1,:]

array([ 6,  7,  8,  9, 10])

In [21]:
#getting a range of elements
a[0, 2:]

array([3, 4, 5])

In [27]:
a[0, 0:4:2]

array([1, 3])

In [29]:
a[0:-2:2]

array([[1, 2, 3, 4, 5]])

In [32]:
#changing the values
a[0,1] = 20
print(a)

[[ 1 20  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [37]:
a[:,2]=[6,6,6]
print(a)

[[ 1 20  6  4  5]
 [ 6  7  6  9 10]
 [11 12  6 14 15]]


In [41]:
#3d array

b = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
b[0,1,1]

4

In [43]:
b[1, 1, 1]

8

In [44]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [46]:
b[:, 0, :]

array([[1, 2],
       [5, 6]])

##### initializing different types of arrays

##### all zeros

In [51]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
np.zeros((5,2,1))

array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]])

In [53]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [54]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [56]:
np.ones((5,2,1), dtype = 'int16')

array([[[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]]], dtype=int16)

##### np.ones but with different number

In [58]:
np.full((2,3,3), 5, dtype = "int16")

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]], dtype=int16)

In [59]:
#to have an array with same shape but made just of a single number
np.full_like(b, 99)

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

##### Random Arrays

In [60]:
#random decimal numbers
np.random.rand(4,2)

array([[0.14316437, 0.37848104],
       [0.26119578, 0.30547276],
       [0.07042496, 0.58966958],
       [0.86075663, 0.81859413]])

In [66]:
#random integer numbers
np.random.randint(4,7, size = (4,2))

array([[6, 6],
       [4, 5],
       [4, 5],
       [5, 5]])

In [67]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
#repeat an array
arr = np.array([[1,2,3]])
ri = np.repeat(arr, 3, axis = 1)
ri

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [74]:
arr = np.array([[1,2,3]])
ri = np.repeat(arr, 3, axis = 0)
ri

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [79]:
n = np.ones((5,5), dtype = 'int16')
n

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [82]:
#exercise to create the matrix using the above functions
n[1:4,1:4] = 0
n[2,2]=9
n

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [87]:
x = np.ones((5,5))
z = np.zeros((3,3))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [91]:
x[1:4, 1:4] = z
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

##### caution during copying arrays

In [94]:
a = np.array([1,2,3,4,5])
b = a.copy()

##### now if we moddify b it wont change a

##### Mathematics

In [97]:
a = np.array([1,2,3,4,5,6,7])

In [98]:
a+2

array([3, 4, 5, 6, 7, 8, 9])

In [99]:
a-2

array([-1,  0,  1,  2,  3,  4,  5])

In [100]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14])

In [101]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [102]:
a%2

array([1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [103]:
a//2

array([0, 1, 1, 2, 2, 3, 3], dtype=int32)

In [105]:
b = np.array([7,8,9,4,5,6,1])

In [106]:
a+b

array([ 8, 10, 12,  8, 10, 12,  8])

In [107]:
b+a

array([ 8, 10, 12,  8, 10, 12,  8])

In [108]:
a*a

array([ 1,  4,  9, 16, 25, 36, 49])

In [113]:
#taking sin of all the values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ])

In [116]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225])

In [117]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798])

##### Linear Algebra

In [128]:
x = np.ones((2,3))
print(x)

y = np.full((3,2),2)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [129]:
np.matmul(x,y)

array([[6., 6.],
       [6., 6.]])

In [130]:
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [131]:
stats = np.array([1,2,3,4,5,6,7,8,9,10])
stats

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
np.mean(stats)

5.5

In [133]:
np.median(stats)

5.5

In [135]:
np.min(stats)

1

In [136]:
np.max(stats)

10

In [ ]:
np.